"""Build the Pixel Art theme's icons from pixel-icons.pxa into smt/theme.css.

    python smt/icons/build.py

Each 9x9 frame becomes an SVG mask (one rect run per row, crispEdges), keyed by
the Material Symbols ligature the page writes. theme.css paints the mask in
currentColor at a whole multiple of 9px, so every art pixel lands on a screen
pixel and the icon takes whatever colour its button or text has.

The generated block sits between the BEGIN/END markers in theme.css and is
replaced wholesale on each run. The .pxa is parsed with the PixelForge library
in /pixelforge/files, the same tool used to draw it.
"""
import os
import re
import sys
from urllib.parse import quote

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.join(ROOT, "pixelforge", "files"))
from pxlib import fmt  # noqa: E402

SRC = os.path.join(HERE, "pixel-icons.pxa")
CSS = os.path.join(ROOT, "smt", "theme.css")
BEGIN = "/* BEGIN pixel-icons (generated by smt/icons/build.py from smt/icons/pixel-icons.pxa; do not edit) */"
END = "/* END pixel-icons */"
INK = "X"


def runs(frame, key):
    parts = []
    for y, row in enumerate(frame.rows):
        for m in re.finditer(re.escape(key) + "+", row):
            parts.append("M%d %dh%dv1H%dz" % (m.start(), y, m.end() - m.start(), m.start()))
    return "".join(parts)


def data_uri(frame):
    svg = ("<svg xmlns='http://www.w3.org/2000/svg' width='%d' height='%d' viewBox='0 0 %d %d' "
           "shape-rendering='crispEdges'><path d='%s'/></svg>"
           % (frame.width, frame.height, frame.width, frame.height, runs(frame, INK)))
    return "url(\"data:image/svg+xml," + quote(svg, safe="/:=' ") + "\")"


def build():
    sprite = fmt.load(SRC)
    errors, _ = fmt.validate(sprite)
    if errors:
        sys.exit("pixel-icons.pxa is invalid:\n  " + "\n  ".join(errors))
    size = sprite.width
    names = [f.name for f in sprite.frames]
    sel = ",".join('[data-icon="%s"]' % n for n in names)
    lines = [
        BEGIN,
        "html[data-style=\"pixelart\"] .material-symbols-outlined:is(%s) {" % sel,
        "    width:%dpx; height:%dpx; width:round(up, 1em, %dpx); height:round(up, 1em, %dpx);" % (size * 2, size * 2, size, size),
        "    flex-shrink:0; overflow:hidden; filter:none; -webkit-text-fill-color:transparent; background-color:currentColor;",
        "    -webkit-mask:var(--px-icon) center / 100% 100% no-repeat; mask:var(--px-icon) center / 100% 100% no-repeat; }",
    ]
    for f in sprite.frames:
        lines.append("html[data-style=\"pixelart\"] [data-icon=\"%s\"] { --px-icon:%s; }" % (f.name, data_uri(f)))
    lines.append(END)
    block = "\n".join(lines)

    css = open(CSS, encoding="utf-8").read()
    if BEGIN in css:
        start = css.index(BEGIN)
        stop = css.index(END, start) + len(END)
        css = css[:start] + block + css[stop:]
    else:
        sys.exit("markers not found in theme.css; add them where the block belongs")
    open(CSS, "w", encoding="utf-8", newline="\n").write(css)
    print("wrote %d icons (%dx%d) into %s" % (len(names), size, size, os.path.relpath(CSS, ROOT)))


if __name__ == "__main__":
    build()
