"""Build the Pixel Art theme's icons and window frame into smt/theme.css.

    python smt/icons/build.py

pixel-icons.pxa: each 9x9 frame becomes an SVG mask (one rect run per row,
crispEdges), keyed by the Material Symbols ligature the page writes. theme.css
paints the mask in currentColor at a whole multiple of 9px, so every art pixel
lands on a screen pixel.

pixel-frame.pxa: each frame becomes a coloured SVG 9-slice for border-image,
once per light/dark mode, with its role keys painted from FRAME_COLORS.

The generated block sits between the BEGIN/END markers in theme.css and is
replaced wholesale on each run. The .pxa files are parsed with the PixelForge
library in /pixelforge/files, the same tool used to draw them.
"""
import os
import re
import sys
from urllib.parse import quote

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.join(ROOT, "pixelforge", "files"))
from pxlib import fmt  # noqa: E402

SRC = os.path.join(HERE, "pixel-icons.pxa")
FRAME_SRC = os.path.join(HERE, "pixel-frame.pxa")
CSS = os.path.join(ROOT, "smt", "theme.css")
BEGIN = "/* BEGIN pixel-icons (generated by smt/icons/build.py from smt/icons/*.pxa; do not edit) */"
END = "/* END pixel-icons */"
INK = "X"

# Frame role colours per mode (keys as in pixel-frame.pxa).
FRAME_COLORS = {
    "dark":  {"K": "#0B0C18", "H": "#C4C4F2", "M": "#6B6BAE", "L": "#45457E", "k": "#15162A"},
    "light": {"K": "#1C2A12", "H": "#FFFFFF", "M": "#8DB07A", "L": "#4A6A3A", "k": "#2E4222"},
}


def runs(frame, key):
    parts = []
    for y, row in enumerate(frame.rows):
        for m in re.finditer(re.escape(key) + "+", row):
            parts.append("M%d %dh%dv1H%dz" % (m.start(), y, m.end() - m.start(), m.start()))
    return "".join(parts)


def uri(frame, body):
    svg = ("<svg xmlns='http://www.w3.org/2000/svg' width='%d' height='%d' viewBox='0 0 %d %d' "
           "shape-rendering='crispEdges'>%s</svg>" % (frame.width, frame.height, frame.width, frame.height, body))
    return "url(\"data:image/svg+xml," + quote(svg, safe="/:=' ") + "\")"


def data_uri(frame):
    return uri(frame, "<path d='%s'/>" % runs(frame, INK))


def frame_uri(frame, colors):
    keys = sorted({ch for row in frame.rows for ch in row if ch in colors})
    return uri(frame, "".join("<path fill='%s' d='%s'/>" % (colors[k], runs(frame, k)) for k in keys))


def build():
    sprite = fmt.load(SRC)
    errors, _ = fmt.validate(sprite)
    if errors:
        sys.exit("pixel-icons.pxa is invalid:\n  " + "\n  ".join(errors))
    size = sprite.width
    names = [f.name for f in sprite.frames]
    sel = ",".join('[data-icon="%s"]' % n for n in names)
    lines = [
        BEGIN,
        "html[data-style=\"pixelart\"] .material-symbols-outlined:is(%s) {" % sel,
        "    width:%dpx; height:%dpx; width:round(up, 1em, %dpx); height:round(up, 1em, %dpx);" % (size * 2, size * 2, size, size),
        "    flex-shrink:0; overflow:hidden; filter:none; -webkit-text-fill-color:transparent; background-color:currentColor;",
        "    -webkit-mask:var(--px-icon) center / 100% 100% no-repeat; mask:var(--px-icon) center / 100% 100% no-repeat; }",
    ]
    for f in sprite.frames:
        lines.append("html[data-style=\"pixelart\"] [data-icon=\"%s\"] { --px-icon:%s; }" % (f.name, data_uri(f)))
    frames = fmt.load(FRAME_SRC)
    errors, _ = fmt.validate(frames)
    if errors:
        sys.exit("pixel-frame.pxa is invalid:\n  " + "\n  ".join(errors))
    for mode, colors in FRAME_COLORS.items():
        for f in frames.frames:
            lines.append("html[data-mode=\"%s\"][data-style=\"pixelart\"] { --px-frame-%s:%s; }" % (mode, f.name, frame_uri(f, colors)))
    lines.append(END)
    block = "\n".join(lines)

    css = open(CSS, encoding="utf-8").read()
    if BEGIN in css:
        start = css.index(BEGIN)
        stop = css.index(END, start) + len(END)
        css = css[:start] + block + css[stop:]
    else:
        sys.exit("markers not found in theme.css; add them where the block belongs")
    open(CSS, "w", encoding="utf-8", newline="\n").write(css)
    print("wrote %d icons (%dx%d) and %d frame(s) into %s"
          % (len(names), size, size, len(frames.frames), os.path.relpath(CSS, ROOT)))


if __name__ == "__main__":
    build()
