// Cache-busting for a site with no build step.
//
// isaiart.com sits behind Cloudflare, which (with the browser) caches .js files for hours
// but always serves index.html fresh. After a deploy, a fresh page could run with stale
// modules ("Cannot set properties of null") until the cache expired.
//
// This writes an import map into index.html that points every module at
// `file.js?v=<hash of its contents>`, plus the same fingerprints for the model files.
// A changed file gets a new URL (so nothing stale is ever served); unchanged files keep
// theirs (so they stay cached).
//
//   node tools/stamp.mjs          rewrite index.html
//   node tools/stamp.mjs --check  exit 1 if index.html is out of date (the tests run this)
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const hash = p => createHash('sha1').update(readFileSync(join(root, p))).digest('hex').slice(0, 10);

export function stampBlock() {
  const files = [...readdirSync(join(root, 'js')).filter(f => f.endsWith('.js')).sort().map(f => `js/${f}`), 'vendor/three.module.min.js'];
  const imports = Object.fromEntries(files.map(f => [`./${f}`, `./${f}?v=${hash(f)}`]));
  const assets = { 'models/models.json': hash('models/models.json'), 'models/models.bin': hash('models/models.bin') };
  // painted icons (tools/icons.py): icons.js draws these instead of its SVGs where one exists
  let icons = []; try { icons = readdirSync(join(root, 'art', 'icons')).filter(f => f.endsWith('.webp')).sort(); } catch { /* none yet */ }
  for (const f of icons) assets[`art/icons/${f}`] = hash(`art/icons/${f}`);
  // painted frames: each becomes a CSS variable (--frame-<name>) holding its fingerprinted url
  let frames = []; try { frames = readdirSync(join(root, 'art', 'frames')).filter(f => f.endsWith('.webp')).sort(); } catch { /* none yet */ }
  const vars = frames.map(f => `--frame-${f.replace('.webp', '')}: url(art/frames/${f}?v=${hash(`art/frames/${f}`)});`).join(' ');
  return `<!-- stamp:begin (generated by tools/stamp.mjs: run it after changing any js or model file) -->
  <script type="importmap">${JSON.stringify({ imports }, null, 1).replace(/\n\s*/g, ' ')}</script>
  <script>window.__villagesV = ${JSON.stringify(assets)};</script>${vars ? `
  <style>:root { ${vars} }</style>` : ''}
  <!-- stamp:end -->`;
}

const START = /<!-- stamp:begin[\s\S]*?<!-- stamp:end -->/;
export function stampedHtml(html) {
  if (!START.test(html)) throw new Error('index.html has no stamp markers');
  return html.replace(START, stampBlock());
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const p = join(root, 'index.html'), html = readFileSync(p, 'utf8'), next = stampedHtml(html);
  if (process.argv.includes('--check')) {
    if (next !== html) { console.error('index.html is stale: run node tools/stamp.mjs'); process.exit(1); }
    console.log('stamp up to date');
  } else if (next !== html) { writeFileSync(p, next); console.log('index.html stamped'); }
  else console.log('stamp already up to date');
}
