#!/usr/bin/env python3
"""Compile timer/sprites/*.pxa into timer/sprites.js.

The .pxa files are the source of the art; sprites.js is a build artifact so the
page needs no fetch at runtime. Regenerate after editing any sprite:

    python3 timer/build_sprites.py

Requires pixelforge, which lives in this repo at /pixelforge/files.
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(os.path.dirname(HERE), "pixelforge", "files"))

from pxlib import fmt  # noqa: E402  (needs the path above)

SRC = os.path.join(HERE, "sprites")
OUT = os.path.join(HERE, "sprites.js")


def hexcolor(rgba):
    r, g, b, a = rgba
    if a == 0:
        return None
    return "#%02x%02x%02x" % (r, g, b)


def compile_sprite(path):
    sprite = fmt.load(path)
    errors, _ = fmt.validate(sprite)
    if errors:
        raise SystemExit("%s: %s" % (os.path.basename(path), "; ".join(errors)))

    used = sprite.used_keys()
    palette = {}
    for key in sorted(used):
        if key == ".":
            continue
        color = hexcolor(sprite.color(key))
        if color is None:
            raise SystemExit("%s: key %r has no color" % (os.path.basename(path), key))
        palette[key] = color

    return {
        "w": sprite.width,
        "h": sprite.height,
        "pal": palette,
        "order": [f.name for f in sprite.frames],
        "frames": dict((f.name, list(f.rows)) for f in sprite.frames),
    }


def main():
    names = sorted(n for n in os.listdir(SRC) if n.endswith(".pxa"))
    if not names:
        raise SystemExit("no .pxa files in %s" % SRC)

    data = {}
    for name in names:
        data[name[:-4]] = compile_sprite(os.path.join(SRC, name))

    body = ",\n".join(
        '  %s: %s' % (json.dumps(key), json.dumps(value, separators=(",", ":")))
        for key, value in sorted(data.items())
    )
    with open(OUT, "w") as handle:
        handle.write(
            "/* Generated by timer/build_sprites.py from timer/sprites/*.pxa.\n"
            "   Do not edit by hand -- edit the .pxa text and rebuild. */\n"
            "window.TIDE_SPRITES = {\n%s\n};\n" % body
        )

    cells = sum(s["w"] * s["h"] * len(s["order"]) for s in data.values())
    print("%s  %d sprites, %d frames, %d cells, %.1f KB"
          % (os.path.relpath(OUT), len(data),
             sum(len(s["order"]) for s in data.values()), cells,
             os.path.getsize(OUT) / 1024.0))


if __name__ == "__main__":
    main()
